services:
  - type: web
    name: mundomagicocm
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: python manage.py migrate && python manage.py seed && gunicorn mundomagico.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DEBUG
        value: "0"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com,mundomagicocm.com.br,www.mundomagicocm.com.br
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com,https://mundomagicocm.com.br,https://www.mundomagicocm.com.br
      - key: ADMIN_USER
        value: admbrinquedos@gmail.com
      - key: ADMIN_PASSWORD
        value: mundomagico123
      - key: DATABASE_URL
        fromDatabase:
          name: mundomagicocm-db
          property: connectionString

databases:
  - name: mundomagicocm-db
    plan: free
